import type { CSSProperties } from "react";

export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "flex-start", gap: 14, marginBottom: 6 } satisfies CSSProperties,
  headerText: { flex: 1 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  accent: { color: "var(--accent)" } satisfies CSSProperties,
  sub: { fontSize: 13, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: "18px 0 14px",
  } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  grid: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,

  card: {
    display: "flex",
    gap: 16,
    padding: 18,
    borderRadius: 12,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    borderLeft: "3px solid var(--accent)",
  } satisfies CSSProperties,
  cardBody: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rule: { fontSize: 15, fontWeight: 600, fontStyle: "italic", marginBottom: 12 } satisfies CSSProperties,
  evidenceBox: {
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-base)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 12px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  evidenceLink: {
    color: "var(--text-secondary)",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "12px 14px",
    fontSize: 13,
    lineHeight: 1.5,
    whiteSpace: "pre",
    overflowX: "auto",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  confRow: { display: "flex", alignItems: "center", gap: 10, marginTop: 12 } satisfies CSSProperties,
  confLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  confBar: { width: 160 } satisfies CSSProperties,
  confPct: { fontSize: 12.5, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,

  actions: { display: "flex", flexDirection: "column", gap: 8, width: 132 } satisfies CSSProperties,
  editRow: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 12 } satisfies CSSProperties,

  // modal
  footer: { display: "flex", justifyContent: "flex-end", gap: 10 } satisfies CSSProperties,
  body: { padding: "20px 24px", width: 640, maxWidth: "100%" } satisfies CSSProperties,
  banner: {
    display: "flex",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    background: "var(--bg-base)",
    border: "1px solid var(--border)",
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 18,
  } satisfies CSSProperties,
  toggleRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
} as const;
